### ISSUE TITLE
Doesn't work for small towns

### ISSUE THREAD

**Issue by rassie** [NonsenseInc/osm-radius-map#3]
This query does not return any relations and therefore can't show a radius: https://nonsenseinc.github.io/osm-radius-map/index.htm?wd=Q999522&radius=15

**Comment by fx99-D** [comment]
Buckenreuth  https://www.openstreetmap.org/node/5236099921 is not a community with some sort of administrative boundary. 
Therefore, overpass cannot find anything.

**Comment by rassie** [comment]
OK, thanks, I suppose this is done then :)
