### ISSUE TITLE
Es werden keine Anfragen mehr richtig beantwortet.

### ISSUE THREAD

**Issue by gmbo** [NonsenseInc/osm-radius-map#4]
Hallo,
Seit die Adresse des Testservers in der Mailingliste steht, gibt es viele Anfragen und es scheinen die Overpass slots belegt zu sein, denn zur Zeit wird grundsätzlich Wesel zurückgegeben.
es könnte mit http://www.overpass-api.de/api/status der Status des Overpass-Servers erfragt werden und erst dann mit der Abfrage begonnen werden wenn noch Slots frei sind, da sonst recht schnell die overpassapi die Abfragen blockt.
Gruß 
Gisbert

**Comment by NonsenseInc** [comment]
Wenn Wesel zurückgegeben wird, dann funktioniert die Overpass API. Das Problem liegt wahrscheinlich an falschen Paramtern in der URL.

Zum Test:
https://nonsenseinc.github.io/osm-radius-map/index.htm?wd=Q2100&radius=15 ist Duisburg mit 15 km
https://nonsenseinc.github.io/osm-radius-map/index.htm?wd=Q14868&radius=5 ist Buxtehude mit 5 km

Wenn die Parameter nicht vorhanden sind, wird standartmäßig Wesel mit 15km benutzt.
Wenn die Overpass API Probleme macht, bleibt die Karte in der Weltansicht stehen.

Debugging sollte mit der Javascript-Konsole möglich sein, bis das Script dahngehend ausgebaut ist.

Ich wäre für Feedback dankbar, um zu wissen, ob das Problem damit behoben ist!

**Comment by gmbo** [comment]
Danke für die schnelle Antwort, hatte das auch inzwischen herausbekommen, dass der Timeout nicht nach overpass gesendet wird und als Parameter wd= erwartet wird.
Hatte das auf der OSM Mailingliste weitergegeben und bekam als Rückmeldungen, dass vieles funktioniert aber einiges nicht .
Habe das gerade mal getestet und bekomme für Q504585
https://nonsenseinc.github.io/osm-radius-map/index.htm?wd=Q504585&radius=15

requesting overpass data: https://overpass-api.de/api/interpreter?data=%5Bout:json%5D;…elation%5B%22wikidata%22=%22Q504585%22%5D;%20);%20out%20geom; index.js:26:9
this might take some seconds... index.js:27:9

Uncaught TypeError: t is undefined
    G https://cdn.jsdelivr.net/npm/@turf/turf@v6.2.0-alpha.3/turf.min.js:1
    ey https://cdn.jsdelivr.net/npm/@turf/turf@v6.2.0-alpha.3/turf.min.js:27
    onload https://nonsenseinc.github.io/osm-radius-map/index.js:42
    EventHandlerNonNull* https://nonsenseinc.github.io/osm-radius-map/index.js:34
habe dann 

nok Baiersdorf:
https://nonsenseinc.github.io/osm-radius-map/index.htm?wd=Q163423

nok Bubenreuth:
https://nonsenseinc.github.io/osm-radius-map/index.htm?wd=Q503669

nok Uttenreuth:
https://nonsenseinc.github.io/osm-radius-map/index.htm?wd=Q2503881

nok Verwaltungsgemeinschaft Uttenreuth:
https://nonsenseinc.github.io/osm-radius-map/index.htm?wd=Q1311707
 nicht mehr getestet.

**Comment by NonsenseInc** [comment]
Das andere Problem habe ich nach #6 bewegt und behoben. Damit schließe ich auch dieses.
